name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Example for Node.js dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install  # Or 'pip install -r requirements.txt' for Python

      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
